import reflex as rx
import os
from google import genai
from google.genai import types
import random
import string
import logging


class ImageGenState(rx.State):
    """State for the Image Generator feature."""

    prompt: str = ""
    style: str = "Realistic"
    generated_image: str = ""
    is_generating: bool = False
    error_message: str = ""
    styles: list[str] = [
        "Realistic",
        "Cartoon",
        "Artistic",
        "Cyberpunk",
        "Vintage",
        "Minimalist",
    ]

    @rx.event
    async def generate_image(self):
        """Call Gemini API to generate an image from text."""
        if not self.prompt:
            self.error_message = "Please enter a prompt."
            return
        api_key = os.getenv("GOOGLE_API_KEY")
        if not api_key:
            self.error_message = "Google API Key not found. Please set GOOGLE_API_KEY environment variable."
            return
        self.is_generating = True
        self.error_message = ""
        self.generated_image = ""
        yield
        try:
            client = genai.Client(api_key=api_key)
            full_prompt = f"Create a {self.style.lower()} image of {self.prompt}. High quality, sports theme."
            response = client.models.generate_content(
                model="gemini-2.5-flash-image",
                contents=full_prompt,
                config=types.GenerateContentConfig(
                    response_modalities=["IMAGE"],
                    image_config=types.ImageConfig(aspect_ratio="1:1"),
                ),
            )
            generated_image_data = None
            if response.parts:
                for part in response.parts:
                    if part.inline_data:
                        generated_image_data = part.inline_data.data
                        break
            if generated_image_data:
                upload_dir = rx.get_upload_dir()
                upload_dir.mkdir(parents=True, exist_ok=True)
                output_filename = f"gen_{''.join(random.choices(string.ascii_lowercase + string.digits, k=8))}.png"
                output_path = upload_dir / output_filename
                with open(output_path, "wb") as f:
                    f.write(generated_image_data)
                self.generated_image = output_filename
            else:
                self.error_message = "No image generated by the model."
        except Exception as e:
            logging.exception(f"Generation Error: {e}")
            self.error_message = f"Generation Error: {str(e)}"
        finally:
            self.is_generating = False